services:
  gameboxed-front:
    image: gameboxed-front:1.0
    ports:
      - "3000:80"
    depends_on:
      - gameboxed-back

  gameboxed-back:
    image: gameboxed-back:1.0
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/gameboxed
      SPRING_DATASOURCE_USERNAME: gameboxed-back
      SPRING_DATASOURCE_PASSWORD: gameboxed-back
      SPRING_DATA_REDIS_HOST: redis
      GOOGLE_CLIENT_ID: ${GOOGLE_CLIENT_ID}
      GOOGLE_CLIENT_SECRET: ${GOOGLE_CLIENT_SECRET}
    depends_on:
      - db
      - redis

  db:
    image: postgres:16
    environment:
      POSTGRES_USER: gameboxed-back
      POSTGRES_PASSWORD: gameboxed-back
      POSTGRES_DB: gameboxed
    ports:
      - "5432:5432"

  redis:
    image: redis:7.2.4
    ports:
      - "6379:6379"