services:
  gameboxed-back:
    image: gameboxed-back:1.0
    ports:
      - "8080:8080"
    depends_on:
      - db
  db:
    image: postgres:16
    environment:
      POSTGRES_USER: gameboxed-back
      POSTGRES_PASSWORD: gameboxed-back
      POSTGRES_DB: gameboxed